version: '3'
services:
  nginx:
    image: nginx:1.17.8-alpine
    container_name: yu-sns-nginx
    ports:
      - 80:80
    volumes:
      - ./bindfs/nginx/conf:/etc/nginx
      - ./bindfs/nginx/root:/usr/share/nginx/html
  ldap:
    build: ./build/ldap
    container_name: yu-sns-openldap
    volumes:
      - ./bindfs/ldap/data:/var/lib/openldap/openldap-data
      - ./build/ldap/slapd.conf:/etc/openldap/slapd.conf
  app1:
    image: node:12.16.1-alpine3.10
    container_name: yu-sns-app1
    ports:
      - 55555:55555
    volumes:
      - ./bindfs/yusns-auth:/app
    working_dir: /app
    entrypoint: ['node', '/app/index.js']
